In [165]:
print ("Hello World")

Hello World


## Basic Operators

In [166]:
10 + 5 * 3

25

In [167]:
(10 + 5) * 3

45

In [168]:
20 / 4

5.0

In [169]:
20 // 4

5

In [170]:
21//4

5

In [171]:
21 % 4

1

In [172]:
5 ** 5

3125

In [173]:
5 + 3 * 2 - 8 / 4 ** 2

10.5

In [174]:
50 > 100

False

In [175]:
33 == 33.0

True

In [176]:
'hello' != 'world'

True

In [177]:
len("python") >= 5

True

## Variables and Data Types

In [178]:
city = 'New York'
print (city)

New York


In [179]:
city = 'New York'
city = city.replace ('New York', 'London')
print(city)

London


In [180]:
score = 100
score -= 25
score *= 2
score

150

1st_place # false

first-place # false

_first_place

for # false

FirstPlace

In [181]:
99 # integer
"99" # string
99.0 # float
False # bool
None # NoneType

In [182]:
price_str = "25.99"
price_float = float(price_str)
print (price_str)
print (price_float)


25.99
25.99


In [183]:
quantity = 3
quantity = str(quantity)
quantity

'3'

In [184]:
print (quantity + " " + 'items.')

3 items.


## Strings in Detail

In [185]:
first_name = "Asgar"
last_name = "Aliyev"
full_name = first_name + " " + last_name
separator = "-"*30
print(full_name + " " + separator)

Asgar Aliyev ------------------------------


In [186]:
print("The file is located at: \nC:\\Users\\new_folder\\tabbed_file.txt \nhe said, \"It's a beautiful day.\" ")

The file is located at: 
C:\Users\new_folder\tabbed_file.txt 
he said, "It's a beautiful day." 


In [187]:
print("The file is located at:" "\n" r"C:\Users\new_folder\tabbed_file.txt " "\n" "he said, r""It's a beautiful day.\"")

The file is located at:
C:\Users\new_folder\tabbed_file.txt 
he said, rIt's a beautiful day."


In [188]:
print("""The file is located at:
C:\\Users\\new_folder\\tabbed_file.txt
he said, "It's a beautiful day." """)


The file is located at:
C:\Users\new_folder\tabbed_file.txt
he said, "It's a beautiful day." 


In [189]:
s = "Programming is fun!"
print (s[3])

g


In [190]:
print(s[-1])

!


In [191]:
print(s[11:13])

 i


In [192]:
print(s[3:7])

gram


In [193]:
print(s[::-1])

!nuf si gnimmargorP


In [194]:
tweet = ' WOW, what a great game! #sports #python '

In [195]:
tweet = tweet.lower()
tweet

' wow, what a great game! #sports #python '

In [196]:
print(tweet.strip())

wow, what a great game! #sports #python


In [197]:
tweet.replace("#python", "#DataScience")

' wow, what a great game! #sports #DataScience '

In [198]:
tweet.split()

['wow,', 'what', 'a', 'great', 'game!', '#sports', '#python']

## Basic Input and Output

In [204]:
# name = (input("What is your Name:"))

In [ ]:
# print("Hello" +' ' + name + "!")

Hello !


In [206]:
# year = int(input ('Year:'))
# birth = int(input ('Birth year:'))
# age = year - birth
# print ('your age:' , age)

In [226]:
# item = "laptop"
# price = 1200.50
# quantity = 2
# total_cost = price * quantity
# print (f"item: {item}, \nquantity: {quantity}, \ntotal cost: {total_cost}$")

# 1.2: Data Structures and Control Flow - Exercises 

## Lists

In [227]:
colors = ['red', 'green', 'blue', 'yellow', 'purple']
print (colors)

['red', 'green', 'blue', 'yellow', 'purple']


In [228]:
colors

['red', 'green', 'blue', 'yellow', 'purple']

In [229]:
print(colors[2])

blue


In [230]:
print (colors[::-1])

['purple', 'yellow', 'blue', 'green', 'red']


In [231]:
print (colors[-1])

purple


In [232]:
primary_colors = colors[0:3]
print (primary_colors)

['red', 'green', 'blue']


In [233]:
colors_str= str(colors)
colors_str.replace("yellow", "magenta")


"['red', 'green', 'blue', 'magenta', 'purple']"

In [234]:
colors = ['red', 'green', 'blue', 'yellow', 'purple']
colors[colors.index("yellow")] = "magenta"
print (colors)

['red', 'green', 'blue', 'magenta', 'purple']


In [235]:
colors = ['red', 'green', 'blue', 'yellow', 'purple']
colors[3] = "magenta"
colors.append('cyan')
colors.insert(1, 'orange')
colors.remove('blue')
print (colors)

['red', 'orange', 'green', 'magenta', 'purple', 'cyan']


In [236]:
tic_tac_toe = [['X', 'O', 'X'], ['O', 'X', 'O'], ['X', 'O', ' ']]


In [237]:
print (tic_tac_toe [1][1])

X


In [238]:
tic_tac_toe[2][2] = 'O'

In [239]:
print(tic_tac_toe)

[['X', 'O', 'X'], ['O', 'X', 'O'], ['X', 'O', 'O']]


## Tuples

In [240]:
weekdays = ('monday', 'tuesday', 'wednesday', 'thursday', 'friday')
# errorrrrrr 
weekdays = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
weekdays[0] = 'funday'
print(weekdays[3])
print (weekdays)

thursday
['funday', 'tuesday', 'wednesday', 'thursday', 'friday']


## Conditional Statements

In [241]:
# grade = int(input ("Enyer your grade (0-100): "))
# if 90<= grade <=100 :
#     print ("A")
# elif 80<= grade <=89 :
#     print ("B")
# elif 70<= grade <=79 :
#     print ("C")
# elif 60<= grade <=69 :
#     print ("D")
# elif 0<= grade <60 :
#     print("F")
# else:
#     print ("r u sure?!")

In [242]:
# grade1 = 95
# grade2 = 82
# grade3 = 78
# grade4 = 61
# grade5 = 45

# if 90<= grade1 <=100 :
#     print ("A")
# elif 80<= grade1 <=89 :
#     print ("B")
# elif 70<= grade1 <=79 :
#     print ("C")
# elif 60<= grade1 <=69 :
#     print ("D")
# elif 0<= grade1 <60 :
#     print("F")
# else:
#     print ("r u sure?!")

# if 90<= grade2 <=100 :
#     print ("A")
# elif 80<= grade2 <=89 :
#     print ("B")
# elif 70<= grade2 <=79 :
#     print ("C")
# elif 60<= grade2 <=69 :
#     print ("D")
# elif 0<= grade2 <60 :
#     print("F")
# else:
#     print ("r u sure?!")

# if 90<= grade3 <=100 :
#     print ("A")
# elif 80<= grade3 <=89 :
#     print ("B")
# elif 70<= grade3<=79 :
#     print ("C")
# elif 60<= grade3 <=69 :
#     print ("D")
# elif 0<= grade3 <60 :
#     print("F")
# else:
#     print ("r u sure?!")

# if 90<= grade4 <=100 :
#     print ("A")
# elif 80<= grade4 <=89 :
#     print ("B")
# elif 70<= grade4 <=79 :
#     print ("C")
# elif 60<= grade4 <=69 :
#     print ("D")
# elif 0<= grade4 <60 :
#     print("F")
# else:
#     print ("r u sure?!")

# if 90<= grade5 <=100 :
#     print ("A")
# elif 80<= grade5 <=89 :
#     print ("B")
# elif 70<= grade5 <=79 :
#     print ("C")
# elif 60<= grade5 <=69 :
#     print ("D")
# elif 0<= grade5 <60 :
#     print("F")
# else:
#     print ("r u sure?!")

In [243]:
# print((10 > 5) and (5 < 3))
# print((10 > 5) or (5 < 3))
# print(not (5 == 5))
# print(1 < 3 < 5)
# print(1 < 3 and 3 > 5)

## Loops

In [244]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for even in list1:
    if even % 2 == 0:
        print(even)

2
4
6
8
10


In [245]:
a = 10
while a > 0:
    print(a)
    a-=1
print('liftoff!')

10
9
8
7
6
5
4
3
2
1
liftoff!


In [246]:
i = 0
for i in range(1, 21):
    if i % 3 == 0:
        continue
    if i > 15:
        break
    print(i)

1
2
4
5
7
8
10
11
13
14


In [247]:
words = ['apple', 'banana', 'cherry']
for first_letter in words:
    print(first_letter[0])

a
b
c


In [248]:
numbers = [1, -2, 3, -4 , 5, -6, 7, -8]
for positive in numbers :
    if positive > 0:
        print(positive)
    else:
        print('negative')

1
negative
3
negative
5
negative
7
negative


In [249]:
matrix = [[1 , 2], [3 , 4], [5 , 6]]
for num in matrix: 
    for doubled in num:
        print(doubled*2)

2
4
6
8
10
12


In [250]:
matrix = [[1 , 2], [3 , 4], [5 , 6]]
doubled = [num*2 for r in matrix for num in r]
print(doubled)

[2, 4, 6, 8, 10, 12]


# 1.3: Advanced Data Structures and Functions - Exercises


## Dictionaries

In [251]:
movie = {
    'title':'harry potter',
    'director':'j.k rowling',
    'year': 1997,
    'genre':'fantasy literature',
}

In [252]:
print(movie['title'])
print(movie['genre'])
print(movie['year'])
print(movie['director'])

harry potter
fantasy literature
1997
j.k rowling


In [253]:
movie['rating'] = 9.9
movie

{'title': 'harry potter',
 'director': 'j.k rowling',
 'year': 1997,
 'genre': 'fantasy literature',
 'rating': 9.9}

In [254]:
movie['year'] = f'November {16}, {2001}'
movie

{'title': 'harry potter',
 'director': 'j.k rowling',
 'year': 'November 16, 2001',
 'genre': 'fantasy literature',
 'rating': 9.9}

In [255]:
del movie['genre']

In [256]:
print(movie)

{'title': 'harry potter', 'director': 'j.k rowling', 'year': 'November 16, 2001', 'rating': 9.9}


In [257]:
movie.keys()

dict_keys(['title', 'director', 'year', 'rating'])

In [258]:
movie.values()

dict_values(['harry potter', 'j.k rowling', 'November 16, 2001', 9.9])

In [259]:
m = movie.items()
m

dict_items([('title', 'harry potter'), ('director', 'j.k rowling'), ('year', 'November 16, 2001'), ('rating', 9.9)])

In [260]:
for i in m:
    print(i)

('title', 'harry potter')
('director', 'j.k rowling')
('year', 'November 16, 2001')
('rating', 9.9)


In [261]:
a = [(56,11),(12,3),(13,4),[1,22,3]]
for _ in a:
    print(_)

(56, 11)
(12, 3)
(13, 4)
[1, 22, 3]


In [262]:
if movie.get('producer'):
    print(movie['producer'])
else:
    print('unknown')

unknown


In [263]:
if movie.get('year'):
    print(movie['year'])
else:
    print('unknown')

November 16, 2001


In [264]:
result = "director" in movie
print(result)


True


In [265]:
employees = {
    'Alice': {'role':'developer', 'salary': 80000},
    'Bob' :{'role':'Designer', 'salary': 75000}    
}

In [266]:
print(employees['Alice']['role'])

developer


In [267]:
employees.get('Alice').get('role')

'developer'

In [268]:
employees['Bob']['salary'] = 77000
print(employees['Bob']['salary'])

77000


In [269]:
employees.update({
    'Bob': {'role':'designer','salary':78000}
})

In [270]:
employees.get('Bob')

{'role': 'designer', 'salary': 78000}

In [271]:
employees['Charlie']= {
    'role':'manager','salary':90000
}
print(employees['Charlie'])

{'role': 'manager', 'salary': 90000}


In [272]:
print(employees)

{'Alice': {'role': 'developer', 'salary': 80000}, 'Bob': {'role': 'designer', 'salary': 78000}, 'Charlie': {'role': 'manager', 'salary': 90000}}


## Sets

In [273]:
numbers = [10, 20, 30, 20, 40, 10, 50]
set(numbers)


{10, 20, 30, 40, 50}

In [274]:
unique_numbers = set(numbers)
print(unique_numbers)

{40, 10, 50, 20, 30}


In [275]:
print(sorted(unique_numbers))


[10, 20, 30, 40, 50]


In [276]:
unique_numbers.add(60)
unique_numbers.add(10)
print(sorted(unique_numbers))

[10, 20, 30, 40, 50, 60]


In [277]:
set1 ={1,2,3,4,5}
set2 ={4,5,6,7,8}

In [278]:
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7, 8}

In [279]:
set1.intersection(set2)

{4, 5}

In [280]:
set1.difference(set2)

{1, 2, 3}

In [281]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

print(set1 - set2)

{1, 2, 3}


In [282]:
set2.difference(set1)

{6, 7, 8}

In [283]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

print(set2 - set1)

{8, 6, 7}


In [284]:
set2.symmetric_difference(set1)

{1, 2, 3, 6, 7, 8}

## Functions

In [285]:
def print_greeting():
    print("Hello World!")

In [286]:
print_greeting()

Hello World!


In [287]:
def calculate_area(width, height):
    return (width*height)
print(calculate_area(5,10))

50


In [288]:
def send_email(recipient,body,subject='No Subject'):
    return {
    'To':[recipient],
    'Subject':[subject],
    'Body':[body],
}

In [289]:
print(send_email('hello.world@gmail.com','HELLO!'))


{'To': ['hello.world@gmail.com'], 'Subject': ['No Subject'], 'Body': ['HELLO!']}


In [290]:
def is_positive(x):
    if x == 0:
        return "Neither positive nor negative"
    elif x < 0:
        return False
    else:
        return True

print(is_positive(5))
print(is_positive(-3))
print(is_positive(0))

True
False
Neither positive nor negative


In [291]:
def find_long_words(words, min_length):
    long_words = []
    for word in words:
        if len(word) > min_length:
            long_words.append(word)
    return long_words

In [292]:
words = ['apple','banana','cherry','date','elderberry']
min_length = 5
print(find_long_words(words, min_length))

['banana', 'cherry', 'elderberry']


In [293]:
def find_long_words(words, min_length):
    return [word for word in words if len(word) > min_length]

In [294]:
words = ['apple','banana','cherry','date','elderberry']
min_length = 5
print(find_long_words(words, min_length))

['banana', 'cherry', 'elderberry']


## Scope of Variables

In [295]:
x = 50

def update_x():
    x = 100
    print(f"Inside function: x = {x}")

update_x()
print(f"Outside function: x = {x}")

Inside function: x = 100
Outside function: x = 50


In [296]:
x = 50

def update_x():
    global x
    x = 100
    print(f"Inside function: x = {x}")

update_x()
print(f"Outside function: x = {x}")

Inside function: x = 100
Outside function: x = 100


# 1.4: Advanced Functions and Functional Programming - Exercises

## Lambda Functions

In [297]:
squarer = lambda x: x**2
print(squarer(8))

64


In [298]:
fruits = ['mango', 'apple', 'banana', 'cherry']
sorted_fruits = sorted(fruits, key=lambda last_character: last_character[-1])
print(sorted_fruits)


['banana', 'apple', 'mango', 'cherry']


In [299]:
multipler = lambda x,y: x*y
print(multipler(7,5))

35


## map, filter, and reduce

In [300]:
celsius_temps = [0,10,20,30,40]
farenheit = list(map(lambda celsius: (celsius*9/5)+32, celsius_temps))
print(farenheit)

[32.0, 50.0, 68.0, 86.0, 104.0]


In [301]:
celsius_temps = [0, 10, 20, 30, 40]
farenheit = [(c * 9 / 5) + 32 for c in celsius_temps]
print(farenheit)

[32.0, 50.0, 68.0, 86.0, 104.0]


In [302]:
numbers = [1,15,22,37,44,59,60,72]
filtered = filter(lambda num: (num%2 == 0 or num%3 == 0), numbers)
print(list(filtered))

[15, 22, 44, 60, 72]


In [303]:
numbers = [1,15,22,37,44,59,60,72]
filtered = filter(lambda num: (num%2 == 0 and num%3 == 0), numbers)
print(list(filtered))

[60, 72]


In [304]:
filtered = [num for num in numbers if num % 2 == 0 and num % 3 == 0]
print(filtered)

[60, 72]


In [305]:
numbers = [1,2,3,4,5]
from functools import reduce
reduce(lambda x, y: x+y, numbers)

15

## List, Dictionary, and Set Comprehensions

In [306]:
cubes = list(map(lambda x: x**3, range(1, 11)))
print(cubes)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [307]:
cubes = [x**3 for x in range(1, 11)]
print(cubes)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [308]:
words = ['programming','is','fun','and','powerful']
longwords = map(lambda long: len(long)>5, words)
list(longwords)

[True, False, False, False, True]

In [309]:
words = ['programming','is','fun','and','powerful']
longwords = filter(lambda long: len(long)>5, words)
list(longwords)


['programming', 'powerful']

In [310]:
b = {}
n = 6
a = 1
for i in range(1,n):
    a *= i
    b[i] = a

b

{1: 1, 2: 2, 3: 6, 4: 24, 5: 120}

In [311]:
def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result
factorial(5)

120

In [312]:
numbers = [1, 2, 3, 2, 4, 5, 4, 1]
unique_numbers = set(numbers)
squared_values = [num ** 2 for num in unique_numbers]
print(squared_values)

[1, 4, 9, 16, 25]


In [313]:
numbers = [1, 2, 3, 2, 4, 5, 4, 1]
unique_numbers = (num for num in numbers if numbers.count(num) == 1)
print(list(unique_numbers))


[3, 5]


# Error Handling

In [315]:
# index = int(input('enter an index'))
# my_list = [10, 20, 30, 40]
# try:
#     my_list[index]
# except IndexError :
#     print("error")

In [316]:
# my_list = [10, 20, 30, 40]
# try:
#     index = int(input('enter an index'))
#     my_list[index]
# except IndexError :
#     print("error")
# except ValueError :
#     print("incorrect")

In [320]:
# def divide(a, b):
#     try:
#         result =  a / b
#     except ZeroDivisionError:
#         print('error')
#     else:
#         print('Result:', result)
#     finally:
#         print('division attempt finished.')

# divide(2,0)

## Raising Exceptions and Assertions

In [321]:
# def check_password_strength(password):
#     password = str(password)
#     if len(password) < 8:
#         print('Password is too short!')
#     elif len(password) >= 8:
#        print('Password is strong.')

# try:
#     user_password = input('Enter your password: ')
#     check_password_strength(user_password)
# except Exception as e:
#      print('Error:', e )

In [322]:
# def calculate_discount(price, discount_percent):
#     assert 100 >= discount_percent >= 0, 'invalid discount percentage'
#     return price - price * discount_percent / 100

# print(calculate_discount(20,20))
# print(calculate_discount(20, 11))

# 1.5: Object-Oriented Programming (OOP) - Exercises

## Creating Classes

In [323]:
class Car:
    wheels = 4
    
    def drive(self):
        self.moving = True
        self.stopped = False
        return 'The car is moving.'
    def stop(self):
        self.moving = False
        self.stopped = True
        return 'The car has stopped.'

my_car = Car()
print(my_car.drive())
print(my_car.stop())


The car is moving.
The car has stopped.


In [324]:
class Car:
    wheels = 4
    
    def __init__(self, make = 'Ford', model = 'Mustang', year = 2020):
        self.make = make
        self.model = model
        self.year = year

    def describe(self):
        return f'This is a {self.year} {self.make}, {self.model}.'

In [325]:
class Car:
    wheels = 4
    
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

    def describe(self):
        return f'This is a {self.year} {self.make} {self.model}.'

my_car = Car('Ford', 'Mustang', 2020)
my_car.describe()

'This is a 2020 Ford Mustang.'

## Inheritance

In [326]:
class ElectricCar(Car):
    def __init__(self, make, model, year, battery_size):
        super().__init__(make, model, year)
        self.battery = battery_size

    def describe(self):
        base_description = super().describe().rstrip('.') 
        return f"{base_description} with a {self.battery} kWh"

e_car = ElectricCar('Tesla', 'Y', 2023, 75)
print(e_car.describe())

This is a 2023 Tesla Y with a 75 kWh


In [327]:
class ElectricCar(Car):
    def __init__(self, make, model, year, battery_size):
        super().__init__(make, model, year)
        self.battery = battery_size

    def describe(self):
        return f'This is a {self.year} {self.make} {self.model} with a {self.battery}kWh'
    

e_car = ElectricCar('Tesla', 'Y', 2023, 75)
e_car.describe()

'This is a 2023 Tesla Y with a 75kWh'

In [328]:
# Base Car class
class Car:
    wheels = 4  # class attribute, bütün avtomobillərdə eyni

    def __init__(self, make, model, year):
        self.make = make        # instance attribute
        self.model = model
        self.year = year

    def describe(self):
        """Return a simple description of the car."""
        return f"This is a {self.year} {self.make} {self.model}"

    def start(self):
        print(f"{self.make} {self.model} is starting...")

    def stop(self):
        print(f"{self.make} {self.model} has stopped.")


# Subclass ElectricCar inherits from Car
class ElectricCar(Car):
    def __init__(self, make, model, year, battery_size, range_km):
        super().__init__(make, model, year)  # call parent constructor
        self.battery_size = battery_size      # in kWh
        self.range_km = range_km              # driving range

    def describe(self):
        """Override parent method to include battery info."""
        base = super().describe()  # get description from Car
        return f"{base} with a {self.battery_size} kWh battery and {self.range_km} km range"

    @property
    def charge_time(self):
        """Estimate charging time based on battery size."""
        # simple estimate: 10 km per kWh per hour of charging
        hours = self.battery_size / 10
        return f"Approx {hours:.1f} hours to fully charge"

    def start(self):
        """Override start to show electric car behavior."""
        print(f"{self.make} {self.model} is now silent but ready to drive!")


# Using the classes
my_car = Car('Ford', 'Mustang', 2020)
print(my_car.describe())
my_car.start()
my_car.stop()

tesla = ElectricCar('Tesla', 'Model Y', 2023, 75, 500)
print(tesla.describe())
print(tesla.charge_time)
tesla.start()
tesla.stop()

This is a 2020 Ford Mustang
Ford Mustang is starting...
Ford Mustang has stopped.
This is a 2023 Tesla Model Y with a 75 kWh battery and 500 km range
Approx 7.5 hours to fully charge
Tesla Model Y is now silent but ready to drive!
Tesla Model Y has stopped.


In [329]:
class Car:
    wheels = 4

    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

    def describe(self):
        return f"This is a {self.year} {self.make} {self.model}"

class ElectricCar(Car):
    def __init__(self, make, model, year, battery_size):
        super().__init__(make, model, year)
        self.battery = battery_size

    def describe(self):
        return super().describe() + f" with a {self.battery} kWh"

e_car = ElectricCar('Tesla', 'Y', 2023, 75)
print(e_car.describe())

This is a 2023 Tesla Y with a 75 kWh


## Polymorphism and Encapsulation

In [330]:
class FuelCar(Car):
    def __init__(self, make, model, year, tank_size):
        super().__init__(make, model, year)
        self.tank = tank_size

    def refuel(self):
        print("The car is refueling.")

def electric_refuel(self):
    print("The car is charging.")

ElectricCar.refuel = electric_refuel   # sinifə sonradan metod əlavə etmə

cars = [
    ElectricCar("Tesla", "Model 3", 2024, 82),
    FuelCar("BMW", "M5", 2020, 60)
]

for car in cars:
    car.refuel()


The car is charging.
The car is refueling.


In [331]:
class BankAccount:
    def __init__(self, owner, initial_balance):
        self.owner = owner
        self.__balance = initial_balance

    def deposit(self, amount):
        self.__balance += amount
        return f'{amount} added. New balance: {self.__balance}'
    
    def withdraw(self, amount):
        if amount > self.__balance:
            return 'Insufficient funds!'
        self.__balance -= amount
        return f'{amount} withdrawn. New balance: {self.__balance}'
    
    def get_balance(self):
        return self.__balance
    
asgar = BankAccount('Asgar',100)
print(asgar.deposit(10))
print(asgar.withdraw(20))
asgar.get_balance()

10 added. New balance: 110
20 withdrawn. New balance: 90


90

## More Class Practice

In [332]:
import math

class Line:
    def __init__(self, point1, point2):
        self.point1 = point1
        self.point2 = point2

    def calculate_length(self):
        x1, y1 = self.point1
        x2, y2 = self.point2
        return math.sqrt((x2-x1)**2 + (y2-y1)**2)
    
    def calculate_slope(self):
        x1, y1 = self.point1
        x2, y2 = self.point2
        if x1==x2:
            return None
        return (y2-y1)/(x2-x1)
    
l = Line((0, 0), (0, 3))
print("Length:", l.calculate_length()) 
print("Slope:", l.calculate_slope())  


Length: 3.0
Slope: None


In [333]:
class Rectangle:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        
    def calculate_area(self):
        return f'Area: {self.width * self.height}'
    
    def calculate_perimeter(self):
        return f'Perimeter: {2 * (self.width + self.height)}'
    
rect = Rectangle(5, 10)
print(rect.calculate_area())
print(rect.calculate_perimeter())  

Area: 50
Perimeter: 30


In [334]:
import math

class Cylinder:
    def __init__(self, radius, height):
        self.radius = radius
        self.height = height

    def calculate_volume(self):
        return math.pi * (self.radius**2) * self.height
    
    def calculate_surface_area(self):
        return 2 * math.pi * self.radius * (self.radius + self.height)
    
cyl = Cylinder (3,7)
print(f'Volume: {cyl.calculate_volume():.2f}')
print(f'Surface Area: {cyl.calculate_surface_area():.2f}')

Volume: 197.92
Surface Area: 188.50


## Special Methods

In [335]:
class Book:
    def __init__(self,title, author, pages):
        self.title = title
        self.author = author
        self.pages = pages

    def __str__(self):
        return f'{self.title} by {self.author}, {self.pages} pages'
    
    def __len__(self):
        return self.pages

MyBook1 = Book('1984', 'George Orwell', 328)
print(MyBook1)
print(len(MyBook1))
    

1984 by George Orwell, 328 pages
328


## Data Classes

In [336]:
from dataclasses import dataclass

@dataclass
class Book:
    title : str
    author : str
    pages : int


book1 = Book("Hobbit", "Tolkien", 310)
book2 = Book("Hobbit", "Tolkien", 310)

print(book1 == book2)  # True because dataclass provides __eq__ method
print(book1.__eq__(book2))  # Explicitly calling the equality method

print(book1)  # Uses the auto-generated __repr__ method


True
True
Book(title='Hobbit', author='Tolkien', pages=310)


## Built-in Decorators

In [337]:
class StringUtils:
    @staticmethod
    def reverse(text):
        return text[::-1]
    
print(StringUtils.reverse("Hello World"))

dlroW olleH


In [338]:
class Car:
    def __init__(self, make, model):
        self.make = make
        self.model = model
    @classmethod
    def from_string(cls, car_string):
        make, model = car_string.split('-')
        return cls(make, model)

car1 = Car.from_string("Toyota-Corolla")
print(car1.make, car1.model)
        

Toyota Corolla


In [339]:
class Person:
    def __init__(self, first_name, last_name):
        self.first_name = first_name
        self.last_name = last_name

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'
person = Person('Asgar', 'Aliyev')
print(person.full_name)

Asgar Aliyev


In [340]:
class Person:
    def __init__(self, first_name, last_name):
        self.first_name = first_name
        self.last_name = last_name

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    @full_name.setter
    def full_name(self, name):
        first, last = name.split(" ", 1)
        self.first_name = first
        self.last_name = last


# 1.6: Advanced Data Structures and Iterators - Exercises

## *args and **kwargs

In [341]:
def calculate_average(*args):
    if len(args) == 0:
        return 'Please enter numbers.'
    return sum(args) / len(args)

print(calculate_average(1,2,3,4,5),',', calculate_average(10,20))

3.0 , 15.0


In [342]:
def print_profile(**kwargs):
    for key,value in kwargs.items():
        print(f'{key.capitalize()} : {value}')

print_profile(name="Alex", age=28, city="New York")

Name : Alex
Age : 28
City : New York


In [343]:
def process_order(customer_name, *items, **details):
    print(f'Customer\'s Name: {customer_name}')
    print(f'List of Items Ordered: {", ".join(items)}')
    for key, value in details.items():
        print(f'{key.replace("_", " ").title()}: {value}')

process_order("Bob", "Pizza", "Coke", delivery_time="6 PM", address="123 Main St")

Customer's Name: Bob
List of Items Ordered: Pizza, Coke
Delivery Time: 6 PM
Address: 123 Main St


## Generators and Iterators

In [344]:
def countdown(start):
    while start > 0:
        yield start
        start -=1

for num in countdown(5):
    print(num)

5
4
3
2
1


In [345]:
words = ["hello", "world", "python", "is", "fun"]
word_lengths = (len(word) for word in words)
print(list(word_lengths))
#or result = list(map(len, words))

[5, 5, 6, 2, 3]


## Decorators

In [346]:
def shout(function):
    def wrapper():
        return function().upper()
    return wrapper

@shout
def greet():
    return "Hello, I am a function."

print(greet()) 


HELLO, I AM A FUNCTION.


In [347]:
def repeat(n):
    def decorator(func):
        def wrapper():
            for _ in range(n):
                func()
        return wrapper
    return decorator


@repeat(3)
def say_hi():
    print("Hi!")


say_hi()

Hi!
Hi!
Hi!


## Pathlib

In [348]:
from pathlib import Path

print(Path.cwd())

file_path = Path("data/processed/log.txt")

print(file_path.name)
print(file_path.parent)
print(file_path.suffix)

c:\Users\asgar_b5z8lmb\OneDrive\Masaüstü\div
log.txt
data\processed
.txt


In [349]:
from pathlib import Path

text_file = Path('pathlib_test.txt')
text_file.write_text('Hello from Pathlib!')
content = text_file.read_text()

print(content)

Hello from Pathlib!


In [350]:
from pathlib import Path

dir_path = Path('my_new_folder')
dir_path.mkdir(exist_ok = True)

dir_file_path = dir_path / 'temp.txt'
dir_file_path.write_text('Hello World! Am I a human?')

for item in dir_path.iterdir():
    print(item.name)

temp.txt


## File I/O and Standard Library

In [351]:
from pathlib import Path

lines_to_write = ["First line", "Second line", "Third line"]
my_file = Path('my_file.txt')
my_file.write_text('\n'.join(lines_to_write))

print(my_file.read_text())


First line
Second line
Third line


In [352]:
from collections import Counter

votes = ['red','blue','red','green','blue','red']

print(Counter(votes))

Counter({'red': 3, 'blue': 2, 'green': 1})


In [353]:
from itertools import product

sizes = ['S', 'M', 'L']
colours = ['black', 'white']

final_product = product(sizes, colours)

print(list(final_product))

[('S', 'black'), ('S', 'white'), ('M', 'black'), ('M', 'white'), ('L', 'black'), ('L', 'white')]


# 2.1: NumPy - Exercises

## NumPy Array Creation

In [354]:
import numpy as np

arr1 = [1,2,3,4,5]
arr2 = [[1,2,3], [4,5,6]]
arr3 = np.zeros(10)
arr4 = np.ones((3,4))
arr5 = np.arange(10)
arr6 = np.linspace(0,1,5)

## Array Attributes and Indexing

In [355]:
import numpy as np

arr_random = np.random.randint(1,101, size=(3,3))

print(arr_random.shape)
print(arr_random.ndim)
print(arr_random.size)
print(arr_random.dtype)

(3, 3)
2
9
int32


In [356]:
import numpy as np

arr_a = np.arange(10,20)

print(arr_a[3])
print(arr_a[2:6])

arr_b = np.arange(1,17).reshape(4,4)

print(arr_b) 
print(arr_b[1,2])
print(arr_b[:2, 2:])
print(arr_b[:,2])

13
[12 13 14 15]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7
[[3 4]
 [7 8]]
[ 3  7 11 15]


## Array Operations and Universal Functions (ufuncs)

In [357]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])

print("x + y =", x + y)
print("x * 3 =", x * 3)
print("x ** 2 =", x ** 2)

x + y = [5 7 9]
x * 3 = [3 6 9]
x ** 2 = [1 4 9]


In [358]:
import numpy as np

z = np.array([1, 4, 9, 16, 25])
angles = np.array([0, np.pi/2 , np.pi])

print(np.sqrt(z))
print(np.sin(angles))

[1. 2. 3. 4. 5.]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


## Broadcasting and Aggregate Functions

In [359]:
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
vector = np.array([10,20,30])

print(matrix + vector)

# matrix + np.array([100,200])

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [360]:
import numpy as np 
data = np.random.randint(0,100, size=(3,5))

print(data.sum())
print(data.mean())
print(data.max())
print(data.sum(axis=0))
print(data.mean(axis=1))

725
48.333333333333336
93
[196  91 174 229  35]
[43. 45. 57.]


## Reshaping and Stacking

In [361]:
import numpy as np 

rshparrs = np.arange(12)
rshparrs1 = rshparrs.reshape(3,4) 
rshparrs2 = rshparrs.reshape(4,3)
rshparrs3 = rshparrs2.reshape(2,2,3)

print(rshparrs3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [362]:
import numpy as np 

m1 = np.random.randint(0,100, size=(2,2))
m2 = np.random.randint(0,100, size=(2,2))

print(np.hstack((m1, m2)))
print()
print(np.vstack((m1,m2)))


[[60 40 34 73]
 [19 85 91 67]]

[[60 40]
 [19 85]
 [34 73]
 [91 67]]


## Advanced Operations

In [363]:
import numpy as np

nums = np.arange(-5,6)

nums[nums>0] 
nums[nums<0] = 0

print(nums)

[0 0 0 0 0 0 1 2 3 4 5]


In [364]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

np.dot(v1,v2)

np.int64(32)

In [365]:
mat1 = np.random.randint(0,10, size=(2,2))
mat2 = np.random.randint(0,10, size=(2,2))

np.dot(mat1, mat2)
print(mat1@mat2)

[[27 67]
 [ 6 54]]


# 2.2.1: Pandas Series - Exercises

## Creating Pandas Series

In [366]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [367]:
import pandas as pd

pds = pd.Series([10,20,30,40,50])
pds

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [368]:
import pandas as pd

pdv = pd.Series([5.5, 6.0, 6.5, 7])
pdv.index = ['a','b','c','d']
# pdv = pd.Series([5.5, 6.0, 6.5, 7], index=['a', 'b', 'c', 'd'])
pdv

a    5.5
b    6.0
c    6.5
d    7.0
dtype: float64

In [369]:
import pandas as pd

dictppct = {'London': 8.9 ,'Paris': 2.1, 'New York': 8.4}

pddictppct = pd.Series(dictppct)

for city, pop in pddictppct.items():
    print(f'{city} : {pop}M')


London : 8.9M
Paris : 2.1M
New York : 8.4M


## Indexing and Slicing

In [370]:
import pandas as pd

print(pdv.loc['c'])
print(pdv.iloc[1])

6.5
6.0


In [371]:
import pandas as pd
import string

pdsa = pd.Series(list(string.ascii_lowercase[:10]), index= range(10))

print(pdsa)

pdsa[3:7]

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object


3    d
4    e
5    f
6    g
dtype: object

## Series Operations

In [372]:
import pandas as pd

series1 = pd.Series([1,2,3,4])
series2 = pd.Series([10,20,30,40])

print(series1 + series2)
print(series1 * 5)

0    11
1    22
2    33
3    44
dtype: int64
0     5
1    10
2    15
3    20
dtype: int64


In [373]:
import pandas as pd

series3 = pd.Series([10,20], index=['a','b'])
series4 = pd.Series([30,40], index=['b', 'c'])

print(series3 + series4)

a     NaN
b    50.0
c     NaN
dtype: float64


## Conditional Logic and Filtering

In [374]:
import numpy as np
import pandas as pd

pnp = pd.Series(np.random.randint(-10, 11, size=10))

#pnp[pnp.where(pnp<0).isna()]
print(pnp[pnp>0])

2     3
3     6
4    10
6     8
dtype: int32


In [375]:
pnp.where(pnp>0, 0)

0     0
1     0
2     3
3     6
4    10
5     0
6     8
7     0
8     0
9     0
dtype: int32

## Useful Methods

In [376]:
import pandas as pd

vlcnt = pd.Series(['a','b','a','c','b','a','d','a'])
vlcnt.value_counts()

a    4
b    2
c    1
d    1
Name: count, dtype: int64

In [377]:
import pandas as pd
import numpy as np

srsn = pd.Series([1,4,9,16,25])
srsn.apply(lambda x: np.sqrt(x))

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [378]:
import pandas as pd
import numpy as np

nans = pd.Series([10, 20, 10, 30, np.nan, 40, np.nan, 20])

print(nans.nunique())
print(nans.isnull().mean())
print(nans.isnull().sum())
print()
print(nans.sort_values())
print()
print(nans.dropna())

4
0.25
2

0    10.0
2    10.0
1    20.0
7    20.0
3    30.0
5    40.0
4     NaN
6     NaN
dtype: float64

0    10.0
1    20.0
2    10.0
3    30.0
5    40.0
7    20.0
dtype: float64


# 2.2.2: Pandas DataFrame, I/O, and Multi-Index - Exercises

## DataFrame Creation

In [379]:
%pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [380]:
import pandas as pd

datappi0 = {
    'Product' : ['Apples','Oranges','Bananas'],
    'Price' : [1.5, 1.2, 1.8],
    'InStock' : [True,True,False],
}

dtppi = pd.DataFrame(datappi0)

print(dtppi)

   Product  Price  InStock
0   Apples    1.5     True
1  Oranges    1.2     True
2  Bananas    1.8    False


In [381]:
import pandas as pd

datalist0 = [[1, 'Alice', 100000], [2, 'Bob', 80000], [3, 'Charlie', 120000]]
columnslist0 = ['ID','Name','Salary']

dflst = pd.DataFrame(datalist0, columns=columnslist0)
print(dflst)

   ID     Name  Salary
0   1    Alice  100000
1   2      Bob   80000
2   3  Charlie  120000


## Reading and Writing Data

In [382]:
import pandas as pd

dflst.to_csv('product.csv', index=False)

dflst_from_csv = pd.read_csv('product.csv', index_col = 'ID')

print(dflst_from_csv)

       Name  Salary
ID                 
1     Alice  100000
2       Bob   80000
3   Charlie  120000


In [383]:
%pip install openpyxl

Note: you may need to restart the kernel to use updated packages.


In [384]:
import pandas as pd

dflstxl = dflst.to_excel('employees.xlsx', index=False, sheet_name= 'EmployeeData')

dflstxl = pd.read_excel('employees.xlsx')

print(dflstxl)

   ID     Name  Salary
0   1    Alice  100000
1   2      Bob   80000
2   3  Charlie  120000


## Multi-Index DataFrames

In [385]:
import numpy as np
import pandas as pd

data = {
    ('Q1', 'Sales'): {('USA', 'East'): 100, ('USA', 'West'): 120, ('EU', 'North'): 80},
    ('Q1', 'Profit'): {('USA', 'East'): 20, ('USA', 'West'): 25, ('EU', 'North'): 15},
    ('Q2', 'Sales'): {('USA', 'East'): 110, ('USA', 'West'): 130, ('EU', 'North'): 90},
    ('Q2', 'Profit'): {('USA', 'East'): 22, ('USA', 'West'): 28, ('EU', 'North'): 18}
}

dfdt = pd.DataFrame(data)

dfdt

Q1           Q2       
          Sales Profit Sales Profit
USA East    100     20   110     22
    West    120     25   130     28
EU  North    80     15    90     18

In [386]:
dfdt.loc[:, 'Q1']

Sales  Profit
USA East     100      20
    West     120      25
EU  North     80      15

In [387]:
dfdt.loc[:, 'Q2']

Sales  Profit
USA East     110      22
    West     130      28
EU  North     90      18

In [388]:
dfdt.loc[:, (['Q1','Q2'], 'Profit')]

Q1     Q2
          Profit Profit
USA East      20     22
    West      25     28
EU  North     15     18

In [389]:
dfdt.loc['USA']

Q1           Q2       
     Sales Profit Sales Profit
East   100     20   110     22
West   120     25   130     28

## Stacking and Unstacking

In [390]:
dfdt.stack(level=1)

C:\Users\asgar_b5z8lmb\AppData\Local\Temp\ipykernel_22348\4148203889.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  dfdt.stack(level=1)


Q1   Q2
USA East  Profit   20   22
          Sales   100  110
    West  Profit   25   28
          Sales   120  130
EU  North Profit   15   18
          Sales    80   90

In [391]:
dfdt.unstack(level=0)

Q1                        Q2                    
      Sales        Profit       Sales        Profit      
         EU    USA     EU   USA    EU    USA     EU   USA
East    NaN  100.0    NaN  20.0   NaN  110.0    NaN  22.0
North  80.0    NaN   15.0   NaN  90.0    NaN   18.0   NaN
West    NaN  120.0    NaN  25.0   NaN  130.0    NaN  28.0

## Operations on Indexes and Columns

In [392]:
import pandas as pd

data = {
    'Country': ['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola'],
    'Code': ['AFG', 'ALB', 'DZA', 'AND', 'AGO'],
    'Continent': ['Asia', 'Europe', 'Africa', 'Europe', 'Africa'],
    'Population': [41128771, 2842321, 44903225, 79034, 35588987]
}
df_countries = pd.DataFrame(data)

In [393]:
df_countries

,Country,Code,Continent,Population
0,Afghanistan,AFG,Asia,41128771
1,Albania,ALB,Europe,2842321
2,Algeria,DZA,Africa,44903225
3,Andorra,AND,Europe,79034
4,Angola,AGO,Africa,35588987


In [394]:
df_countries.rename(columns= {'Code':'ISO_Code'}, inplace=True)
df_countries

,Country,ISO_Code,Continent,Population
0,Afghanistan,AFG,Asia,41128771
1,Albania,ALB,Europe,2842321
2,Algeria,DZA,Africa,44903225
3,Andorra,AND,Europe,79034
4,Angola,AGO,Africa,35588987


In [395]:
df_countries.set_index('Country',inplace=True)
print(df_countries)

            ISO_Code Continent  Population
Country                                   
Afghanistan      AFG      Asia    41128771
Albania          ALB    Europe     2842321
Algeria          DZA    Africa    44903225
Andorra          AND    Europe       79034
Angola           AGO    Africa    35588987


In [396]:
df_reset = df_countries.reset_index()

In [397]:
df_multi = df_reset.set_index(['Continent','Country'])

In [398]:
df_multi_sorted = df_multi.sort_index()
print(df_multi_sorted)

                      ISO_Code  Population
Continent Country                         
Africa    Algeria          DZA    44903225
          Angola           AGO    35588987
Asia      Afghanistan      AFG    41128771
Europe    Albania          ALB     2842321
          Andorra          AND       79034


In [399]:
df_result = df_multi_sorted.reset_index()
print(df_result)

  Continent      Country ISO_Code  Population
0    Africa      Algeria      DZA    44903225
1    Africa       Angola      AGO    35588987
2      Asia  Afghanistan      AFG    41128771
3    Europe      Albania      ALB     2842321
4    Europe      Andorra      AND       79034


# 2.2.3: Pandas Operations, Sorting, and Data Cleaning - Exercises

In [400]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 22],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 120000, 90000, 60000]
}
df = pd.DataFrame(data)
df.set_index('Name', inplace=True)

In [401]:
df.Salary
df['Salary']
df.loc[:,'Salary']

Name
Alice       70000
Bob         80000
Charlie    120000
David       90000
Eva         60000
Name: Salary, dtype: int64

In [402]:
df.loc['Charlie']

Age            35
City      Chicago
Salary     120000
Name: Charlie, dtype: object

In [403]:
df.iloc[2]

Age            35
City      Chicago
Salary     120000
Name: Charlie, dtype: object

In [404]:
df.loc['Bob':'David']

,Age,City,Salary
Name,,,
Bob,30,Los Angeles,80000
Charlie,35,Chicago,120000
David,40,Houston,90000


In [405]:
df.iloc[:3,:2]

,Age,City
Name,,
Alice,25,New York
Bob,30,Los Angeles
Charlie,35,Chicago


In [406]:
df.loc[['Alice','Eva'], ['Age','City']]

,Age,City
Name,,
Alice,25,New York
Eva,22,Phoenix


## Filtering and Modifying Data

In [407]:
df.loc[df.loc[:,'Age']>30]

,Age,City,Salary
Name,,,
Charlie,35,Chicago,120000
David,40,Houston,90000


In [408]:
df.loc[(df.loc[:,'City'] == 'Chicago') | (df.loc[:, 'City'] == 'New York')]
df.loc[df.loc[:,'City'].isin(['Chicago','New York'])]

,Age,City,Salary
Name,,,
Alice,25,New York,70000
Charlie,35,Chicago,120000


In [409]:
df.loc[df.loc[:,'Salary']>80000]

,Age,City,Salary
Name,,,
Charlie,35,Chicago,120000
David,40,Houston,90000


In [410]:
df.loc[df.loc[:,'Salary']>80000, ['Salary']]

,Salary
Name,
Charlie,120000
David,90000


In [411]:
df.loc[:,'Bonus'] = df.loc[:,'Salary']*0.1

In [412]:
df.loc[:, 'Senior'] =df.loc[:,'Age'] >= 35

In [413]:
df.drop(columns='City',inplace= True)

In [414]:
df.pop('Bonus')

Name
Alice       7000.0
Bob         8000.0
Charlie    12000.0
David       9000.0
Eva         6000.0
Name: Bonus, dtype: float64

In [415]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 22],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 120000, 90000, 60000]
}
df = pd.DataFrame(data)
df.set_index('Name', inplace=True)


In [416]:
nwdf = df.assign(Monthly_Salary = df.loc[:,'Salary'] /12)

In [417]:
nwdf

,Age,City,Salary,Monthly_Salary
Name,,,,
Alice,25,New York,70000,5833.333333
Bob,30,Los Angeles,80000,6666.666667
Charlie,35,Chicago,120000,10000.000000
David,40,Houston,90000,7500.000000
Eva,22,Phoenix,60000,5000.000000


## Sorting

In [418]:
nwdf.sort_index(ascending=False)

,Age,City,Salary,Monthly_Salary
Name,,,,
Eva,22,Phoenix,60000,5000.000000
David,40,Houston,90000,7500.000000
Charlie,35,Chicago,120000,10000.000000
Bob,30,Los Angeles,80000,6666.666667
Alice,25,New York,70000,5833.333333


In [419]:
nwdf.sort_values('Age', ascending=True)

,Age,City,Salary,Monthly_Salary
Name,,,,
Eva,22,Phoenix,60000,5000.000000
Alice,25,New York,70000,5833.333333
Bob,30,Los Angeles,80000,6666.666667
Charlie,35,Chicago,120000,10000.000000
David,40,Houston,90000,7500.000000


In [420]:
nwdf.sort_values('Salary', ascending=False)

,Age,City,Salary,Monthly_Salary
Name,,,,
Charlie,35,Chicago,120000,10000.000000
David,40,Houston,90000,7500.000000
Bob,30,Los Angeles,80000,6666.666667
Alice,25,New York,70000,5833.333333
Eva,22,Phoenix,60000,5000.000000


## Operations and Aggregation

In [421]:
import pandas as pd
import numpy as np

In [422]:
grades = pd.DataFrame(
    np.random.randint(50, 100, size=(5, 3)),
    columns=['Math', 'Science', 'English'],
    index=['Alice', 'Bob', 'Charlie', 'David', 'Eva']
)
grades

,Math,Science,English
Alice,54,56,85
Bob,88,95,94
Charlie,67,87,68
David,50,92,71
Eva,82,77,78


In [423]:
bonus_grades = grades+5
bonus_grades

,Math,Science,English
Alice,59,61,90
Bob,93,100,99
Charlie,72,92,73
David,55,97,76
Eva,87,82,83


In [424]:
row_wise_mean = bonus_grades.mean(axis=0)
row_wise_mean

Math       73.2
Science    86.4
English    84.2
dtype: float64

In [425]:
column_wise_mean = bonus_grades.mean(axis=1)
column_wise_mean

Alice      70.000000
Bob        97.333333
Charlie    79.000000
David      76.000000
Eva        84.000000
dtype: float64

## Data Cleaning

In [426]:
import pandas as pd
import numpy as np

In [427]:
df_missing = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [10, 11, 12, 13]
})

In [428]:
df_missing.isnull()

,A,B,C
0,False,False,False
1,False,True,False
2,True,True,False
3,False,False,False


In [429]:
df_missing.dropna()

,A,B,C
0,1.0,5.0,10
3,4.0,8.0,13


In [430]:
df_missing.fillna(0)

,A,B,C
0,1.0,5.0,10
1,2.0,0.0,11
2,0.0,0.0,12
3,4.0,8.0,13


In [431]:
df_missing.fillna(df_missing.mean())

,A,B,C
0,1.000000,5.0,10
1,2.000000,6.5,11
2,2.333333,6.5,12
3,4.000000,8.0,13


In [432]:
import pandas as pd
import numpy as np

df_dup = pd.DataFrame({
    'ID': [1, 2, 2, 3, 4, 4],
    'Value': ['A', 'B', 'B', 'C', 'D', 'D']
})

In [433]:
df_dup.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [434]:
df_dup.drop_duplicates(inplace=True)
df_dup

,ID,Value
0,1,A
1,2,B
3,3,C
4,4,D


In [435]:
df_str = pd.DataFrame({
    'Price': ['100', '200', '300', '400']
})

In [436]:
df_str['Price'].dtype

dtype('O')

In [437]:
df_int = df_str.loc[:,'Price'].astype(int)

In [438]:
df_int.dtypes

dtype('int64')

# 2.2.4: Pandas Data Transformation - Exercises

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

## Merging, Joining, and Concatenating

In [3]:
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']}, index=[0, 1])
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']}, index=[2, 3])

df_concat_rows = pd.concat([df1,df2], axis= 0)
df_concat_rows

,A,B
0,A0,B0
1,A1,B1
2,A2,B2
3,A3,B3


In [4]:
df_concat_columns = pd.concat([df1,df2], axis=1)
df_concat_columns

,A,B,A,B
0,A0,B0,NaN,NaN
1,A1,B1,NaN,NaN
2,NaN,NaN,A2,B2
3,NaN,NaN,A3,B3


In [5]:
df3 = pd.DataFrame({'A': ['A4', 'A5'], 'B': ['B4', 'B5']}, index=[0, 1])

df1v3 = pd.concat([df1,df3],axis = 0,ignore_index=True)
df1v3

,A,B
0,A0,B0
1,A1,B1
2,A4,B4
3,A5,B5


In [6]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2'], 'A': ['A0', 'A1', 'A2']})
right = pd.DataFrame({'key': ['K0', 'K1', 'K3'], 'B': ['B0', 'B1', 'B3']})

lr_inner = pd.merge(left, right, on = 'key', how='inner')
lr_inner

,key,A,B
0,K0,A0,B0
1,K1,A1,B1


In [7]:
lr_outer = pd.merge(left,right,on='key',how='outer')
lr_outer

,key,A,B
0,K0,A0,B0
1,K1,A1,B1
2,K2,A2,NaN
3,K3,NaN,B3


In [8]:
lr_right = pd.merge(left, right, on = 'key', how = 'right')
lr_right

,key,A,B
0,K0,A0,B0
1,K1,A1,B1
2,K3,NaN,B3


In [9]:
lr_left = pd.merge(left, right, on = 'key', how='left')
lr_left

,key,A,B
0,K0,A0,B0
1,K1,A1,B1
2,K2,A2,NaN


In [10]:
df_employees = pd.DataFrame({'emp_id': [1, 2, 3, 4], 'name': ['Alice', 'Bob', 'Charlie', 'David']})
df_salaries = pd.DataFrame({'id': [1, 2, 3, 5], 'salary': [50000, 60000, 70000, 80000]})

In [11]:
empid = pd.merge(df_employees, df_salaries, left_on = 'emp_id', right_on= 'id')
empid.drop(columns='id')

,emp_id,name,salary
0,1,Alice,50000
1,2,Bob,60000
2,3,Charlie,70000


## Aggregation and Grouping

In [12]:
import seaborn as sns
planets = sns.load_dataset('planets')

planet_counts = planets.groupby('method')['number'].count()
print(planet_counts)

mean_orbital = planets.groupby('method')['orbital_period'].mean()
print(mean_orbital)

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
Name: number, dtype: int64
method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64


In [13]:
mass_stats = planets.groupby('method')['mass'].agg(['min', 'median', 'max'])
print(mass_stats)

                                  min  median    max
method                                              
Astrometry                        NaN     NaN    NaN
Eclipse Timing Variations      4.2000   5.125   6.05
Imaging                           NaN     NaN    NaN
Microlensing                      NaN     NaN    NaN
Orbital Brightness Modulation     NaN     NaN    NaN
Pulsar Timing                     NaN     NaN    NaN
Pulsation Timing Variations       NaN     NaN    NaN
Radial Velocity                0.0036   1.260  25.00
Transit                        1.4700   1.470   1.47
Transit Timing Variations         NaN     NaN    NaN


In [14]:
import pandas as pd

df = pd.DataFrame({
    'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Points': [10, 15, 10, 20, 10, 5],
    'Assists': [5, 7, 5, 10, 5, 2]
})

team_sums = df.groupby('Team').sum()

filtered_df = df.groupby('Team').filter(lambda x: x['Points'].mean() >= 12)

df['Points_Standardized'] = df.groupby('Team')['Points'].transform(lambda x: x - x.mean())

def double_points(group):
    if group['Assists'].sum() > 10:
        group['Points'] = group['Points'] * 2
    return group

applied_df = df.groupby('Team', group_keys=False).apply(double_points)

## Pivot Tables

In [15]:
titanic = sns.load_dataset('titanic')

pivot1 = titanic.pivot_table('survived', index='sex', columns='class', margins=True)
print(pivot1)

class      First    Second     Third       All
sex                                           
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838


In [16]:
pivot2 = titanic.pivot_table(
    index=['sex', 'embarked'], 
    columns='class', 
    aggfunc={'survived': 'sum', 'fare': 'mean'}
)
print(pivot2)

                       fare                       survived             
class                 First     Second      Third    First Second Third
sex    embarked                                                        
female C         115.640309  25.268457  14.694926       42      7    15
       Q          90.000000  12.350000  10.307833        1      2    24
       S          99.026910  21.912687  18.670077       46     61    33
male   C          93.536707  25.421250   9.352237       17      2    10
       Q          90.000000  12.350000  11.924251        0      0     3
       S          52.949947  19.232474  13.307149       28     15    34


# 2.2.5: Pandas String and DateTime Manipulation - Exercises

## Vectorized String Operations

In [17]:
import pandas as pd
import numpy as np

names = pd.Series(['Alice Smith', 'Bob Jones', 'Charlie Brown', 'David Wilson'])

names_lower = names.str.lower()
names_upper = names.str.upper()
names_len = names.str.len()

print(names_lower)
print(names_upper)
print(names_len)

0      alice smith
1        bob jones
2    charlie brown
3     david wilson
dtype: str
0      ALICE SMITH
1        BOB JONES
2    CHARLIE BROWN
3     DAVID WILSON
dtype: str
0    11
1     9
2    13
3    12
dtype: int64


In [18]:
names_split = names.str.split()
first_names = names.str.split().str.get(0)
first_three = names.str[:3]

print(names_split)
print(first_names)
print(first_three)

0      [Alice, Smith]
1        [Bob, Jones]
2    [Charlie, Brown]
3     [David, Wilson]
dtype: object
0      Alice
1        Bob
2    Charlie
3      David
dtype: object
0    Ali
1    Bob
2    Cha
3    Dav
dtype: str


In [19]:
starts_with_c = names.str.startswith('C')
contains_jones = names.str.contains('Jones')

print(starts_with_c)
print(contains_jones)

0    False
1    False
2     True
3    False
dtype: bool
0    False
1     True
2    False
3    False
dtype: bool


## Date/Time Manipulation

In [20]:
from datetime import datetime

dt_obj = datetime(2023, 1, 1)
dt_str = dt_obj.strftime("%d-%B-%Y")
ts = pd.to_datetime("2023-05-15")

print(dt_str)
print(ts)

01-January-2023
2023-05-15 00:00:00


In [21]:
today = pd.Timestamp.now()
next_week = today + pd.Timedelta(days=7)
range_dates = pd.date_range('2023-01-01', '2023-01-10')
monthly_periods = pd.date_range('2023-01-01', periods=5, freq='ME')

print(next_week)
print(range_dates)
print(monthly_periods)

2026-04-11 19:34:29.248986
DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10'],
              dtype='datetime64[us]', freq='D')
DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31'],
              dtype='datetime64[us]', freq='ME')


## Time Series Analysis

In [22]:
dates = pd.date_range('2023-01-01', periods=6, freq='D')
data = pd.Series([10, 12, 15, 14, 18, 20], index=dates)

val_jan_3 = data.loc['2023-01-03']
val_range = data.loc['2023-01-02':'2023-01-05']

print(val_jan_3)
print(val_range)

15
2023-01-02    12
2023-01-03    15
2023-01-04    14
2023-01-05    18
Freq: D, dtype: int64


In [23]:
dates = pd.date_range('2023-01-01', periods=100, freq='D')
df = pd.DataFrame({'Value': np.random.randn(100)}, index=dates)

monthly_mean = df.resample('ME').mean()
weekly_sum = df.resample('W').sum()

print(monthly_mean)
print(weekly_sum)

               Value
2023-01-31 -0.309326
2023-02-28 -0.082862
2023-03-31  0.299915
2023-04-30  0.257442
               Value
2023-01-01 -1.112137
2023-01-08  1.969663
2023-01-15 -0.442059
2023-01-22 -3.702926
2023-01-29 -3.269855
2023-02-05 -5.703102
2023-02-12 -1.406881
2023-02-19  4.617288
2023-02-26 -1.131287
2023-03-05 -1.898820
2023-03-12  1.504499
2023-03-19  0.917827
2023-03-26  4.693334
2023-04-02  4.163058
2023-04-09 -0.233708
2023-04-16  0.997644


In [24]:
df['Shifted_Value'] = df['Value'].shift(1)
df['Rolling_Mean'] = df['Value'].rolling(window=7).mean()

print(df.head(10))

               Value  Shifted_Value  Rolling_Mean
2023-01-01 -1.112137            NaN           NaN
2023-01-02 -0.276762      -1.112137           NaN
2023-01-03 -0.158314      -0.276762           NaN
2023-01-04  0.674169      -0.158314           NaN
2023-01-05  0.686300       0.674169           NaN
2023-01-06  0.863720       0.686300           NaN
2023-01-07  0.358873       0.863720      0.147978
2023-01-08 -0.178322       0.358873      0.281380
2023-01-09  0.656501      -0.178322      0.414704
2023-01-10 -0.059749       0.656501      0.428785
